console.log (‘____________________________________________’);
console.log (‘’);
console.log (‘|		|		|		|		|		|’);
console.log (‘|		|		|		|		|		|’);
console.log (‘|		|		|		|		|		|’);
console.log (‘____________________________________________’);
console.log (‘’);
console.log (‘|		|		|		|		|		|’);
console.log (‘|		|		|		|		|		|’);
console.log (‘|		|		|		|		|		|’);
console.log (‘____________________________________________’);
console.log (‘’);
console.log (‘|		|		|		|		|		|’);
console.log (‘|		|		|		|		|		|’);
console.log (‘|		|		|		|		|		|’);
console.log (‘____________________________________________’);
console.log (‘’);
console.log (‘|		|		|		|		|		|’);
console.log (‘|		|		|		|		|		|’);
console.log (‘|		|		|		|		|		|’);
console.log (‘____________________________________________’);
console.log (‘’);
console.log (‘|		|		|		|		|		|’);
console.log (‘|		|		|		|		|		|’);
console.log (‘|		|		|		|		|		|’);
console.log (‘____________________________________________’);